//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamentos
    {
        public int ID_Medicamento { get; set; }
        public string Nombre { get; set; }
        public string Presentacion { get; set; }
        public int ID_Tipo_Medicamento { get; set; }
        public decimal Concentracion { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Tipo_Medicamentos Tipo_Medicamentos { get; set; }
    }
}
