//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicamentos()
        {
            this.Tab_Venta_detallada = new HashSet<Tab_Venta_detallada>();
        }
    
        public int ID_Medicamento { get; set; }
        public string Nombre { get; set; }
        public string Presentacion { get; set; }
        public int ID_Tipo_Medicamento { get; set; }
        public decimal Concentracion { get; set; }
        public int Cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_Venta_detallada> Tab_Venta_detallada { get; set; }
        public virtual Tipo_Medicamentos Tipo_Medicamentos { get; set; }
    }
}
