//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioCentroDiurno
    {
        public int ID { get; set; }
        public string Expediente { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Genero { get; set; }
        public string Familiardirecto { get; set; }
        public string Lugarvivienda { get; set; }
        public string Padecimientos { get; set; }
        public string Medicamentos { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Telefono { get; set; }
    }
}
