//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioCentroDiurno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioCentroDiurno()
        {
            this.Tab_Devoluciones = new HashSet<Tab_Devoluciones>();
            this.Tab_Venta = new HashSet<Tab_Venta>();
        }
    
        public int ID { get; set; }
        public string Expediente { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Genero { get; set; }
        public string Familiardirecto { get; set; }
        public string Lugarvivienda { get; set; }
        public string Padecimientos { get; set; }
        public string Medicamentos { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Telefono { get; set; }
        public System.DateTime Fecha_Hora_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_Hora_Salida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_Devoluciones> Tab_Devoluciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_Venta> Tab_Venta { get; set; }
    }
}
